"""Offline diagnostics for the Stage 1 routing checkpoint.

This script intentionally does not retrain the router. It loads the existing
Stage 1 checkpoint, runs it on the strict legal test split, and writes small
JSON/Markdown/LaTeX artifacts for paper and thesis auditing.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import yaml
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from router.features import FeatureExtractor, QueryFeatures
from router.router_model import RouterModel


def _load_json(path: Path) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def _latex_escape(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
    )


def _history_to_text(value: Any) -> str | None:
    if not value:
        return None
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        parts: list[str] = []
        for item in value:
            if isinstance(item, dict):
                q = item.get("question") or item.get("q") or item.get("user")
                a = item.get("answer") or item.get("a") or item.get("assistant")
                if q:
                    parts.append(f"User: {q}")
                if a:
                    parts.append(f"Assistant: {a}")
            else:
                parts.append(str(item))
        return "\n".join(parts) if parts else None
    return str(value)


def _get_base_estimator(model: Any) -> Any:
    if hasattr(model, "feature_importances_"):
        return model
    calibrated = getattr(model, "calibrated_classifiers_", None)
    if calibrated:
        first = calibrated[0]
        return getattr(first, "estimator", None) or getattr(first, "base_estimator", None)
    return None


def _extract_feature_importance(router: RouterModel) -> list[dict[str, Any]]:
    model = getattr(router, "_model", None)
    estimator = _get_base_estimator(model)
    feature_names = QueryFeatures.feature_names()
    rows: list[dict[str, Any]] = []

    booster = getattr(estimator, "get_booster", lambda: None)()
    if booster is not None:
        gain_scores = booster.get_score(importance_type="gain")
        weight_scores = booster.get_score(importance_type="weight")
        for idx, name in enumerate(feature_names):
            key = f"f{idx}"
            rows.append(
                {
                    "rank": 0,
                    "feature": name,
                    "gain": float(gain_scores.get(key, 0.0)),
                    "weight": float(weight_scores.get(key, 0.0)),
                    "importance": float(gain_scores.get(key, 0.0)),
                }
            )
    elif estimator is not None and hasattr(estimator, "feature_importances_"):
        importances = getattr(estimator, "feature_importances_")
        for idx, name in enumerate(feature_names):
            value = float(importances[idx]) if idx < len(importances) else 0.0
            rows.append(
                {
                    "rank": 0,
                    "feature": name,
                    "gain": value,
                    "weight": None,
                    "importance": value,
                }
            )

    rows.sort(key=lambda row: row["importance"], reverse=True)
    for rank, row in enumerate(rows, start=1):
        row["rank"] = rank
    return rows


def _confusion_to_latex(labels: list[str], matrix: list[list[int]]) -> str:
    alignment = "l" + "r" * len(labels)
    header = " & " + " & ".join(_latex_escape(label) for label in labels) + " \\\\"
    lines = [
        "% Auto-generated by scripts/analyze_stage1_router.py",
        "\\begin{tabular}{" + alignment + "}",
        "\\toprule",
        "\\textbf{Gold / Pred.}" + header,
        "\\midrule",
    ]
    for label, row in zip(labels, matrix):
        lines.append(_latex_escape(label) + " & " + " & ".join(str(v) for v in row) + " \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    return "\n".join(lines)


def _feature_importance_to_latex(rows: list[dict[str, Any]], top_k: int) -> str:
    lines = [
        "% Auto-generated by scripts/analyze_stage1_router.py",
        "\\begin{tabular}{rlrr}",
        "\\toprule",
        "\\textbf{Rank} & \\textbf{Feature} & \\textbf{Gain} & \\textbf{Weight} \\\\",
        "\\midrule",
    ]
    for row in rows[:top_k]:
        weight = "-" if row.get("weight") is None else f"{float(row['weight']):.0f}"
        lines.append(
            f"{row['rank']} & {_latex_escape(row['feature'])} & "
            f"{float(row['gain']):.4f} & {weight} \\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}", ""])
    return "\n".join(lines)


def _summary_markdown(
    *,
    dataset_path: Path,
    model_path: Path,
    labels: list[str],
    matrix: list[list[int]],
    report: dict[str, Any],
    feature_rows: list[dict[str, Any]],
    total: int,
) -> str:
    accuracy = float(report.get("accuracy", 0.0))
    macro_f1 = float(report.get("macro_f1_gold_labels", report.get("macro avg", {}).get("f1-score", 0.0)))
    macro_f1_all = float(report.get("macro_f1_all_labels", report.get("macro avg", {}).get("f1-score", 0.0)))
    weighted_f1 = float(report.get("weighted avg", {}).get("f1-score", 0.0))
    lines = [
        "# Stage 1 Router Diagnostics",
        "",
        "This report was generated offline from the existing Stage 1 checkpoint. "
        "No model retraining, vector-store rebuild, graph migration, or Stage 2 call was performed.",
        "",
        "## Inputs",
        "",
        f"- Dataset: `{dataset_path}`",
        f"- Model checkpoint: `{model_path}`",
        f"- Evaluated samples: `{total}`",
        "",
        "## Metrics",
        "",
        f"- Accuracy: `{accuracy:.4f}`",
        f"- Macro-F1 over strict gold labels: `{macro_f1:.4f}`",
        f"- Macro-F1 including zero-support predicted labels: `{macro_f1_all:.4f}`",
        f"- Weighted-F1: `{weighted_f1:.4f}`",
        "",
        "## Confusion Matrix",
        "",
        "| Gold \\ Pred. | " + " | ".join(labels) + " |",
        "|---|" + "|".join("---" for _ in labels) + "|",
    ]
    for label, row in zip(labels, matrix):
        lines.append("| " + label + " | " + " | ".join(str(v) for v in row) + " |")

    lines.extend(["", "## Top Feature Importances", "", "| Rank | Feature | Gain | Weight |", "|---:|---|---:|---:|"])
    for row in feature_rows[:15]:
        weight = "-" if row.get("weight") is None else f"{float(row['weight']):.0f}"
        lines.append(
            f"| {row['rank']} | `{row['feature']}` | {float(row['gain']):.4f} | {weight} |"
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- The strict test split contains three gold retrieval labels: "
            "`dense_retrieval`, `graph_traversal`, and `hybrid_reasoning`.",
            "- If `clarify` appears as a predicted label, it is counted as a false positive in this strict split.",
            "- The primary Macro-F1 above averages only labels with gold support in the strict split; the "
            "secondary Macro-F1 includes zero-support predicted labels such as `clarify`.",
            "- Feature importance is extracted from the loaded XGBoost estimator inside the calibrated wrapper when available.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze an existing Stage 1 router checkpoint.")
    parser.add_argument("--config", default="configs/config.yaml")
    parser.add_argument("--test-file", default="qa_pipeline/data/legal_strict/test.json")
    parser.add_argument("--model-path", default=None)
    parser.add_argument("--output-dir", default="results")
    parser.add_argument("--top-k", type=int, default=15)
    args = parser.parse_args()

    config_path = Path(args.config)
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    dataset_path = Path(args.test_file)
    model_path = Path(args.model_path or config["router"]["stage1"]["model_path"])
    output_dir = Path(args.output_dir)

    if not dataset_path.exists():
        raise FileNotFoundError(f"Strict test file not found: {dataset_path}")
    if not model_path.exists():
        raise FileNotFoundError(f"Stage 1 checkpoint not found: {model_path}")

    data = _load_json(dataset_path)
    extractor = FeatureExtractor(config=config)
    router = RouterModel(config)
    if not router.load(str(model_path)):
        raise RuntimeError(f"Could not load Stage 1 checkpoint: {model_path}")

    y_true: list[str] = []
    y_pred: list[str] = []
    confidences: list[float] = []

    for item in data:
        question = (item.get("question") or item.get("query") or "").strip()
        label = (item.get("routing_label") or item.get("expected_route") or "").strip()
        if not question or not label:
            continue
        history = _history_to_text(item.get("history"))
        features = extractor.extract(question, history=history)
        output = router.predict(features)
        y_true.append(label)
        y_pred.append(output.route)
        confidences.append(float(output.confidence))

    if not y_true:
        raise RuntimeError(f"No labeled samples found in {dataset_path}")

    labels = [label for label in RouterModel.CLASS_LABELS if label in set(y_true) | set(y_pred)]
    gold_labels = [label for label in RouterModel.CLASS_LABELS if label in set(y_true)]
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    report = classification_report(y_true, y_pred, labels=labels, output_dict=True, zero_division=0)
    report["accuracy"] = float(accuracy_score(y_true, y_pred))
    report["macro_f1_all_labels"] = float(f1_score(y_true, y_pred, labels=labels, average="macro", zero_division=0))
    report["macro_f1_gold_labels"] = float(f1_score(y_true, y_pred, labels=gold_labels, average="macro", zero_division=0))
    report["weighted_f1"] = float(f1_score(y_true, y_pred, labels=gold_labels, average="weighted", zero_division=0))
    report["metadata"] = {
        "config": str(config_path),
        "dataset": str(dataset_path),
        "model_path": str(model_path),
        "total_samples": len(y_true),
        "labels": labels,
        "gold_labels": gold_labels,
        "avg_confidence": float(np.mean(confidences)) if confidences else 0.0,
    }

    cm_payload = {
        "labels": labels,
        "matrix": cm.tolist(),
        "gold_counts": {label: int(sum(1 for y in y_true if y == label)) for label in labels},
        "prediction_counts": {label: int(sum(1 for y in y_pred if y == label)) for label in labels},
    }
    feature_rows = _extract_feature_importance(router)

    _write_json(output_dir / "stage1_confusion_matrix.json", cm_payload)
    _write_json(output_dir / "stage1_classification_report.json", report)
    _write_json(
        output_dir / "stage1_feature_importance.json",
        {
            "model_path": str(model_path),
            "importance_type": "gain",
            "features": feature_rows,
        },
    )

    (output_dir / "stage1_diagnostics_summary.md").write_text(
        _summary_markdown(
            dataset_path=dataset_path,
            model_path=model_path,
            labels=labels,
            matrix=cm.tolist(),
            report=report,
            feature_rows=feature_rows,
            total=len(y_true),
        ),
        encoding="utf-8",
    )
    (output_dir / "latex_stage1_confusion_matrix.tex").write_text(
        _confusion_to_latex(labels, cm.tolist()),
        encoding="utf-8",
    )
    (output_dir / "latex_stage1_feature_importance.tex").write_text(
        _feature_importance_to_latex(feature_rows, args.top_k),
        encoding="utf-8",
    )

    print(f"Stage 1 diagnostics written to {output_dir}")
    print(f"Accuracy={report['accuracy']:.4f} Macro-F1={report['macro_f1_gold_labels']:.4f}")


if __name__ == "__main__":
    main()
